apiVersion: batch/v1 
kind: CronJob
metadata:
  name: roleta-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 20
      parallelism: 2
      completions: 3
      template:
        spec:
          containers:
          - name: job
            image: kubedevio/roleta
            args:
              - "-w"
              - "15"
              - "-c"
              - "2"
              - "-m"
              - "5"
          restartPolicy: Never