apiVersion: v1 
kind: LimitRange
metadata:
  name: limite-container
spec:
  limits:
    - max:
        cpu: "800m"
        memory: "900Mi"
      min:
        cpu: "150m"
        memory: "99Mi"
      default:
        cpu: "250m"
        memory: "128Mi"
      defaultRequest:
        cpu: "150m"
        memory: "100Mi"
      type: Container
