apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstreplicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: mycontainer
          image: kubedevio/nginx-color:green