apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myfirstdeployment
spec:
  replicas: 25
  selector:
    matchLabels:
      app: exemplo 
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: mycontainer
          image: kubedevio/nginx-color:green