apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-node
  template:
    metadata:
      labels:
        app: prometheus-node
    spec:
      containers:
        - name: prometheus-node-exporter
          image: prom/node-exporter:v1.0.1
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.listen-address=:9100
          ports:
              - containerPort: 9100
          volumeMounts:
            - mountPath: /host/proc
              name: proc
              readOnly: true
            - mountPath: /host/sys
              name: sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc 
        - name: sys
          hostPath:
           path: /sys