apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec: 
  selector:
    matchLabels:
      app: api
  template: 
    metadata:       
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluster.local; do echo Aguardando o Banco de Dados; sleep 2; done"]
      containers:
      - name: api
        image: devopsguimaraes/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
         requests:
           cpu: "100m"
           memory: "128Mi"
         limits:
           cpu: "300m"
           memory: "256Mi"
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                name: mongodb-secret
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                name: mongodb-secret
