apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
data: 
  Mongo__User: {{ .Values.mongodb.auth.username | b64enc | quote }}
  Mongo__Password: {{ .Values.mongodb.auth.password | b64enc | quote }}
