apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metada:
  name: letsencrypt-homolog
  namespace: cert-manager
spec:
  acme:
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  email: mtguimaraes@gmail.com
  privateKeySecretRef:
    name: letsencrypt-homolog
  solvers:
  - http01:
      ingress:
        class: traefik